### ISSUE TITLE
TSWMod.exe doesn't exist?

### ISSUE THREAD

**Issue by btg611** [Yamazaki93/TSWRDConnector#13]
Hi, 

I've just downloaded the repository and found that there is no TSWMod.exe file found anywhere in the files. I have checked my antivirus to see if it was deleted or quarantined, but it seems it's not in the zip file either. Any help is greatly appreciated.

P.S.
Thank you for providing this program for supporting TSW with raildriver! I'd have done it myself if i had more experience in coding, but unfortunately a small amount of LUA scripting is all the skill I have.

**Comment by Yamazaki93** [comment]
Hi,
You will need to download it from the release page https://github.com/Yamazaki93/TSWRDConnector/releases and click `TSWMod.zip`
The compiled binary is there, the repository only contains code

**Comment by btg611** [comment]
Oof, I guess I was in the wrong place then! Thanks for your help!
