### ISSUE TITLE
Unable to sync RailDriver with NEC GP38-2

### ISSUE THREAD

**Issue by moparacker** [Yamazaki93/TSWRDConnector#7]
Loco(s): GP38-2
Map: NewRochelleNewarkMap 
Scenario(s):  Terminal Switch, New York Switcher, Back Track

Unable to sync game with RailDriver, even though RailDriver shows "CL". Connector is showing correct map, but will not register the loco.

Attempted restarting of Connector, no fix. Tried with V0.1.4 and V0.1.5, same result.

Affects all GP38-2's on all NEC maps.

**Comment by Yamazaki93** [comment]
This turns out to be that there'a different variant of GP38-2 that's "slightly" different than the other ones, this will be fixed in 0.1.6

**Comment by moparacker** [comment]
Rechecked issue with RDConnector v0.1.6-beta.0, able to sync and drive GP38-2 as expected.

Dynamic brake functions, but has same fluttering issue as GP38-2 on SandPatch. Updated Issue #6 with this info.
