### ISSUE TITLE
GP38-2/SD40-2 - Moving Indy Brake to 0% causes Auto Brake handle to move

### ISSUE THREAD

**Issue by moparacker** [Yamazaki93/TSWRDConnector#8]
Loco(s): GP38-2, SD40-2
Map: SandPatch
Scenario(s): Multiple
RD Connector version: V0.1.5

GP38-2:

When the Indy brake is set to "100%" and the Auto Brake is set to "Full Service", there are no issues.

When the Indy Brake is set to "0%", the Auto Brake moves from "Full Service" to "Handle Off" and stays there. When the Indy Brake is move above 1%, the Auto Brake moves back to "Full Service". The Auto Brake handle on the RailDriver is never touched.

SD40-2:

When the Indy brake is set to "100%" and the Auto Brake is set to "Full Service", there are no issues.

When the Indy Brake is set to "0%", the Auto Brake moves from "Full Service" to "Handle Off" and dances between these two settings. When the Indy Brake is move above 1%, the Auto Brake moves back to "Full Service". The Auto Brake handle on the RailDriver is never touched. I have a screen capture video of this is desired.

Issue was not present in V0.1.4 and is new in V0.1.5.

**Comment by moparacker** [comment]
Issue was not present in V0.1.4 and is new in V0.1.5.

**Comment by Yamazaki93** [comment]
I think this may be a limitation we are hitting. If I see the problem correctly, RD sends the value back in a byte (so integer basically). TSW deals with continuous value (0 ~ 1 in float). So this percision issue may be enough to cause the notch to jump if the auto brake is not set "firmly" at the position. This means we may not be able to do much, I can try to add in some small "null zone" to see if this improves the issue.

After testing in current develop version, I can't reproduce this so hopefully it's a fix

**Comment by moparacker** [comment]
Rechecked using v0.1.6-beta.0 and no issues with either locomotive.

Issue appears to be corrected with new version.
